export const GOAL_SELECTION = 'GOAL_SELECTION'
export const PRACTICE = 'PRACTICE'
export const REFLECTION = 'REFLECTION'
export const COMPLETE = 'COMPLETE'

export const CYCLE_STATES = [
  GOAL_SELECTION,
  PRACTICE,
  REFLECTION,
  COMPLETE,
]
