export const IN_PROGRESS = 'IN_PROGRESS'
export const REVIEW = 'REVIEW'
export const CLOSED_FOR_REVIEW = 'CLOSED_FOR_REVIEW'
export const CLOSED = 'CLOSED'

export const PROJECT_DEFAULT_EXPECTED_HOURS = 38

export const PROJECT_STATES = [
  IN_PROGRESS,
  REVIEW,
  CLOSED_FOR_REVIEW,
  CLOSED,
]

const dayMS = 24 * 60 * 60 * 1000

export const PROJECT_REVIEW_TIMEOUT_DAYS = 3
export const PROJECT_REVIEW_TIMEOUT_MS = PROJECT_REVIEW_TIMEOUT_DAYS * dayMS
export const TRUSTED_PROJECT_REVIEW_START_DATE = new Date('2017-03-03 00:00:00 GMT-0800')
