import keyMirror from 'keymirror'

export default keyMirror({
  UPDATE_JWT: null,
  AUTHORIZATION_ERROR: null,
  UNAUTHENTICATED_ERROR: null,
  DISMISS_ERROR: null,

  APP_SHOW_LOADING: null,
  APP_HIDE_LOADING: null,

  FETCH_DATA_REQUEST: null,
  FETCH_DATA_FAILURE: null,
  FETCH_DATA_SUCCESS: null,

  ADD_INVITE_CODE_TO_CHAPTER_REQUEST: null,
  ADD_INVITE_CODE_TO_CHAPTER_SUCCESS: null,
  ADD_INVITE_CODE_TO_CHAPTER_FAILURE: null,

  FIND_CHAPTERS_REQUEST: null,
  FIND_CHAPTERS_SUCCESS: null,
  FIND_CHAPTERS_FAILURE: null,

  FIND_MEMBERS_REQUEST: null,
  FIND_MEMBERS_SUCCESS: null,
  FIND_MEMBERS_FAILURE: null,

  FIND_PROJECTS_REQUEST: null,
  FIND_PROJECTS_SUCCESS: null,
  FIND_PROJECTS_FAILURE: null,

  FIND_USERS_REQUEST: null,
  FIND_USERS_SUCCESS: null,
  FIND_USERS_FAILURE: null,

  GET_CHAPTER_REQUEST: null,
  GET_CHAPTER_SUCCESS: null,
  GET_CHAPTER_FAILURE: null,

  GET_CYCLE_VOTING_RESULTS_REQUEST: null,
  GET_CYCLE_VOTING_RESULTS_SUCCESS: null,
  GET_CYCLE_VOTING_RESULTS_FAILURE: null,

  GET_PROJECT_REQUEST: null,
  GET_PROJECT_SUCCESS: null,
  GET_PROJECT_FAILURE: null,

  GET_PROJECT_SUMMARY_REQUEST: null,
  GET_PROJECT_SUMMARY_SUCCESS: null,
  GET_PROJECT_SUMMARY_FAILURE: null,

  FIND_SURVEYS_REQUEST: null,
  FIND_SURVEYS_SUCCESS: null,
  FIND_SURVEYS_FAILURE: null,

  GET_SURVEY_REQUEST: null,
  GET_SURVEY_SUCCESS: null,
  GET_SURVEY_FAILURE: null,

  GET_USER_SUMMARY_REQUEST: null,
  GET_USER_SUMMARY_SUCCESS: null,
  GET_USER_SUMMARY_FAILURE: null,

  DEACTIVATE_USER_REQUEST: null,
  DEACTIVATE_USER_SUCCESS: null,
  DEACTIVATE_USER_FAILURE: null,

  REACTIVATE_USER_REQUEST: null,
  REACTIVATE_USER_SUCCESS: null,
  REACTIVATE_USER_FAILURE: null,

  IMPORT_PROJECT_REQUEST: null,
  IMPORT_PROJECT_SUCCESS: null,
  IMPORT_PROJECT_FAILURE: null,

  REASSIGN_MEMBERS_TO_CHAPTER_REQUEST: null,
  REASSIGN_MEMBERS_TO_CHAPTER_SUCCESS: null,
  REASSIGN_MEMBERS_TO_CHAPTER_FAILURE: null,

  UPDATE_USER_REQUEST: null,
  UPDATE_USER_SUCCESS: null,
  UPDATE_USER_FAILURE: null,

  RECEIVED_CYCLE_VOTING_RESULTS: null,

  SAVE_CHAPTER_REQUEST: null,
  SAVE_CHAPTER_SUCCESS: null,
  SAVE_CHAPTER_FAILURE: null,

  SUBMIT_SURVEY_REQUEST: null,
  SUBMIT_SURVEY_SUCCESS: null,
  SUBMIT_SURVEY_FAILURE: null,

  SET_SURVEY_GROUP: null,

  SAVE_SURVEY_RESPONSES_REQUEST: null,
  SAVE_SURVEY_RESPONSES_SUCCESS: null,
  SAVE_SURVEY_RESPONSES_FAILURE: null,

  UNLOCK_SURVEY_REQUEST: null,
  UNLOCK_SURVEY_SUCCESS: null,
  UNLOCK_SURVEY_FAILURE: null,

  LOCK_SURVEY_REQUEST: null,
  LOCK_SURVEY_SUCCESS: null,
  LOCK_SURVEY_FAILURE: null,

  DELETE_PROJECT_REQUEST: null,
  DELETE_PROJECT_SUCCESS: null,
  DELETE_PROJECT_FAILURE: null,

  FIND_PHASES_REQUEST: null,
  FIND_PHASES_SUCCESS: null,
  FIND_PHASES_FAILURE: null,

  FIND_PHASE_SUMMARIES_REQUEST: null,
  FIND_PHASE_SUMMARIES_SUCCESS: null,
  FIND_PHASE_SUMMARIES_FAILURE: null,
})
